-- ==============================================================================
-- CREATE SECOND LARRY ACCOUNT (larrysecrets@gmail.com)
-- ==============================================================================
--
-- Source: larry@uglydogadventures.com (ID: b7486f8d-c69f-4069-acfd-a6cb22bdd664)
-- Target: larrysecrets@gmail.com (new UUID will be generated by Supabase Auth)
--
-- This script will:
-- 1. Create auth user for larrysecrets@gmail.com via Supabase Auth API
-- 2. Copy profile data (except email, with is_demo_account = false for LIVE mode)
-- 3. Copy all 9 pets with new IDs
-- 4. Skip copying claims and vet bills (start fresh for testing submissions)
--
-- NOTE: Review carefully before executing!
-- ==============================================================================

-- ==============================================================================
-- IMPORTANT NOTE ABOUT SCHEMA
-- ==============================================================================
-- The profiles table does NOT have a "test_mode" field.
-- The field that indicates demo/test status is "is_demo_account" (boolean).
-- For larry@uglydogadventures.com, is_demo_account is NULL or can be set to false.
-- For larrysecrets@gmail.com, we will explicitly set is_demo_account = false
-- to ensure it behaves like a LIVE beta tester account.
-- ==============================================================================


-- ------------------------------------------------------------------------------
-- STEP 1: Create auth user for larrysecrets@gmail.com
-- ------------------------------------------------------------------------------
-- This MUST be done via Supabase Auth API or Dashboard, NOT via SQL
--
-- METHOD 1: Via Supabase Dashboard
-- 1. Go to Authentication > Users
-- 2. Click "Add user"
-- 3. Email: larrysecrets@gmail.com
-- 4. Auto-generate password or set one
-- 5. Confirm email automatically
--
-- METHOD 2: Via JavaScript/Node (recommended for automation)
--
-- await supabase.auth.admin.createUser({
--   email: 'larrysecrets@gmail.com',
--   email_confirm: true,
--   password: 'GENERATE_SECURE_PASSWORD_HERE',
--   user_metadata: {}
-- })
--
-- After creating the user, note down the UUID returned by Supabase Auth.
-- Replace all instances of 'NEW_USER_ID_PLACEHOLDER' below with that actual UUID.
-- ------------------------------------------------------------------------------


-- ------------------------------------------------------------------------------
-- STEP 2: Copy profile data from larry@uglydogadventures.com
-- ------------------------------------------------------------------------------
-- All fields are copied EXCEPT:
--   - id (use new user ID from auth.users)
--   - email (set to larrysecrets@gmail.com)
--   - is_demo_account (set to false for LIVE testing)
-- ------------------------------------------------------------------------------

INSERT INTO public.profiles (
  id,
  email,
  full_name,
  phone,
  address,
  email_reminders,
  weekly_summaries,
  deadline_alerts,
  default_expense_category,
  default_time_period,
  insurance_company,
  filing_deadline_days,
  phone_number,
  timezone,
  sms_opt_in,
  signature,
  policy_number,
  is_admin,
  onboarding_complete,
  city,
  state,
  zip,
  is_demo_account
)
SELECT
  'NEW_USER_ID_PLACEHOLDER'::uuid,           -- Replace with actual new user ID from Step 1
  'larrysecrets@gmail.com',                   -- New email
  'Larry Levin',                              -- Same name
  '+13123050403',                             -- Same phone
  '2010 East Hillman Circle',                 -- Same address
  false,                                      -- email_reminders
  false,                                      -- weekly_summaries
  false,                                      -- deadline_alerts
  'insured',                                  -- default_expense_category
  'all_time',                                 -- default_time_period
  'Healthy Paws',                             -- insurance_company
  90,                                         -- filing_deadline_days
  NULL,                                       -- phone_number
  'America/Los_Angeles',                      -- timezone
  true,                                       -- sms_opt_in
  signature,                                  -- Copy signature from original
  NULL,                                       -- policy_number
  false,                                      -- is_admin
  true,                                       -- onboarding_complete
  'Orange',                                   -- city (will use original, adjust if needed)
  'CA',                                       -- state (will use original, adjust if needed)
  '92867',                                    -- zip (will use original, adjust if needed)
  false                                       -- is_demo_account = false (LIVE mode for beta testing!)
FROM public.profiles
WHERE id = 'b7486f8d-c69f-4069-acfd-a6cb22bdd664';  -- larry@uglydogadventures.com


-- ------------------------------------------------------------------------------
-- STEP 3: Copy all 9 pets from larry@uglydogadventures.com
-- ------------------------------------------------------------------------------
-- Each pet gets:
--   - New UUID (generated automatically)
--   - References new user_id
--   - All other pet data copied as-is
-- ------------------------------------------------------------------------------

INSERT INTO public.pets (
  user_id,
  name,
  species,
  color,
  photo_url,
  insurance_company,
  policy_number,
  owner_name,
  owner_address,
  owner_phone,
  filing_deadline_days
)
SELECT
  'NEW_USER_ID_PLACEHOLDER'::uuid,           -- Replace with actual new user ID
  name,
  species,
  color,
  photo_url,
  insurance_company,
  policy_number,
  owner_name,
  owner_address,
  owner_phone,
  filing_deadline_days
FROM public.pets
WHERE user_id = 'b7486f8d-c69f-4069-acfd-a6cb22bdd664'  -- larry@uglydogadventures.com
ORDER BY created_at;  -- Preserve creation order


-- ------------------------------------------------------------------------------
-- STEP 4: DO NOT copy claims, medications, or vet bills
-- ------------------------------------------------------------------------------
-- These tables will remain empty for larrysecrets@gmail.com
-- This allows fresh submissions for testing purposes
-- ------------------------------------------------------------------------------


-- ==============================================================================
-- VERIFICATION QUERIES (Run AFTER executing the above)
-- ==============================================================================

-- Verify new user exists in auth.users
-- SELECT * FROM auth.users WHERE email = 'larrysecrets@gmail.com';

-- Verify new profile was created
-- SELECT * FROM public.profiles WHERE email = 'larrysecrets@gmail.com';

-- Verify pets were copied (should be 9 pets)
-- SELECT COUNT(*), user_id FROM public.pets
-- WHERE user_id = 'NEW_USER_ID_PLACEHOLDER'
-- GROUP BY user_id;

-- Verify no claims exist (should return 0)
-- SELECT COUNT(*) FROM public.claims
-- WHERE user_id = 'NEW_USER_ID_PLACEHOLDER';

-- Verify no medications exist (should return 0)
-- SELECT COUNT(*) FROM public.medications
-- WHERE user_id = 'NEW_USER_ID_PLACEHOLDER';


-- ==============================================================================
-- SUMMARY OF WHAT THIS SCRIPT DOES
-- ==============================================================================
-- 1. Creates new auth user larrysecrets@gmail.com (via Supabase Auth API)
-- 2. Copies profile from larry@uglydogadventures.com with these changes:
--      - New user ID
--      - Email: larrysecrets@gmail.com
--      - is_demo_account: false (LIVE MODE like beta testers)
-- 3. Copies all 9 pets with:
--      - New pet IDs (auto-generated)
--      - New user_id reference
--      - All original pet data preserved
-- 4. Does NOT copy:
--      - Claims
--      - Medications
--      - Vet bills
--      - Any other dependent data
--
-- This gives larrysecrets@gmail.com a fresh account with all pets but no history,
-- ready for live submissions like a real beta tester.
-- ==============================================================================

-- ==============================================================================
-- END OF SCRIPT - DO NOT EXECUTE UNTIL APPROVED BY USER
-- ==============================================================================
