-- ==============================================================================
-- CREATE SECOND LARRY ACCOUNT (larrysecrets@gmail.com)
-- ==============================================================================
--
-- Source: larry@dogstrainedright.com (ID: 3e51432f-52f6-4964-9e26-8db1aeb76115)
-- Target: larrysecrets@gmail.com (new UUID will be generated)
--
-- This script will:
-- 1. Create auth user for larrysecrets@gmail.com
-- 2. Copy profile data (except email and test mode indicators)
-- 3. Copy pet(s) with new IDs
-- 4. Skip copying claims and vet bills (start fresh)
--
-- NOTE: This script is for REVIEW ONLY. Do NOT execute until approved.
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- STEP 1: Create auth.user for larrysecrets@gmail.com
-- ------------------------------------------------------------------------------
-- This must be done via Supabase Auth API or Dashboard, not via SQL
-- The new user ID will be generated by Supabase Auth
-- After creation, get the new user ID and use it in STEP 2 below

-- MANUAL STEP: Create user via Supabase Dashboard or use:
-- await supabase.auth.admin.createUser({
--   email: 'larrysecrets@gmail.com',
--   email_confirm: true,
--   user_metadata: {}
-- })
--
-- IMPORTANT: Replace 'NEW_USER_ID_HERE' below with the actual UUID from above


-- ------------------------------------------------------------------------------
-- STEP 2: Copy profile data from larry@dogstrainedright.com
-- ------------------------------------------------------------------------------
INSERT INTO public.profiles (
  id,
  email,
  full_name,
  phone,
  address,
  email_reminders,
  weekly_summaries,
  deadline_alerts,
  default_expense_category,
  default_time_period,
  insurance_company,
  filing_deadline_days,
  phone_number,
  timezone,
  sms_opt_in,
  signature,
  policy_number,
  is_admin,
  onboarding_complete,
  city,
  state,
  zip,
  is_demo_account
)
SELECT
  'NEW_USER_ID_HERE'::uuid,                    -- Replace with actual new user ID
  'larrysecrets@gmail.com',                    -- New email
  full_name,
  phone,
  address,
  email_reminders,
  weekly_summaries,
  deadline_alerts,
  default_expense_category,
  default_time_period,
  insurance_company,
  filing_deadline_days,
  phone_number,
  timezone,
  sms_opt_in,
  signature,
  policy_number,
  is_admin,
  onboarding_complete,
  city,
  state,
  zip,
  false                                         -- NOT a demo account (live like beta testers)
FROM public.profiles
WHERE id = '3e51432f-52f6-4964-9e26-8db1aeb76115';  -- larry@dogstrainedright.com


-- ------------------------------------------------------------------------------
-- STEP 3: Copy pet(s) from larry@dogstrainedright.com
-- ------------------------------------------------------------------------------
-- For each pet, we need to:
-- 1. Generate new pet ID
-- 2. Associate with new user ID
-- 3. Keep all other pet data the same

-- Pet: Scrappy (original ID: will be queried)
-- We'll use a CTE to get the original pet data

WITH original_pet AS (
  SELECT
    name,
    species,
    color,
    photo_url,
    insurance_company,
    policy_number,
    owner_name,
    owner_address,
    owner_phone,
    filing_deadline_days
  FROM public.pets
  WHERE user_id = '3e51432f-52f6-4964-9e26-8db1aeb76115'  -- larry@dogstrainedright.com
  LIMIT 1  -- Should only be 1 pet (Scrappy)
)
INSERT INTO public.pets (
  id,
  user_id,
  name,
  species,
  color,
  photo_url,
  insurance_company,
  policy_number,
  owner_name,
  owner_address,
  owner_phone,
  filing_deadline_days
)
SELECT
  gen_random_uuid(),                            -- New pet ID
  'NEW_USER_ID_HERE'::uuid,                    -- Replace with actual new user ID
  name,
  species,
  color,
  photo_url,
  insurance_company,
  policy_number,
  owner_name,
  owner_address,
  owner_phone,
  filing_deadline_days
FROM original_pet;


-- ------------------------------------------------------------------------------
-- STEP 4: DO NOT copy claims or vet bills - start fresh
-- ------------------------------------------------------------------------------
-- Claims and vet bills will NOT be copied to the new account
-- This allows larrysecrets@gmail.com to start with a clean slate


-- ==============================================================================
-- VERIFICATION QUERIES (Run after script execution)
-- ==============================================================================

-- Verify new user profile
-- SELECT * FROM public.profiles WHERE email = 'larrysecrets@gmail.com';

-- Verify new pet(s)
-- SELECT * FROM public.pets WHERE user_id = 'NEW_USER_ID_HERE';

-- Verify no claims exist
-- SELECT COUNT(*) FROM public.claims WHERE user_id = 'NEW_USER_ID_HERE';
-- Should return 0

-- ==============================================================================
-- END OF SCRIPT
-- ==============================================================================
